---
title: "Analysis of Full Bayesian Regression"
output: html_notebook
---


```{r}
library(dplyr)
library(tidyverse)
library(report)
```


## Load data

```{r}
training_df <- select(read_csv('../data/bankruptcy_train_am.csv'), -X1)
dim(training_df)
```


```{r}
par(mfrow=c(3,2))

plot(training_df$Attr8, training_df$class, xlab = "book value of equity / total liabilities", ylab = "bankcruptcy")

plot(training_df$Attr40, training_df$class, xlab = "(current assets - inventory - receivables) / short-term liabilities", ylab = "bankcruptcy")

plot(training_df$Attr42, training_df$class, xlab = " profit on operating activities / sales", ylab = "bankcruptcy")

plot(training_df$Attr12, training_df$class, xlab = "gross profit / short-term liabilities", ylab = "bankcruptcy")

plot(training_df$Attr59, training_df$class, xlab = "long-term liabilities / equity", ylab = "bankcruptcy")

```




## Load the model
```{r}
lpost1 <- readRDS('../model/post1.rds')
```

```{r}
report(lpost1)
```



```{r}
summary(lpost1)
```
```{r}
round(posterior_interval(lpost1, prob = 0.95), 2)
```

```{r}
library(bayestestR)
library(insight)
```


```{r}
describe_posterior(lpost1)
```

```{r}
library(insight)
```

```{r}
posteriors <- insight::get_parameters(lpost1)

head(posteriors)  # Show the first 6 rows

```

```{r}
nrow(posteriors)
```

```{r}
library(ggplot2)
```



## Analyse Attr46 : (current assets - inventory) / short-term liabilities
```{r}
ggplot(posteriors, aes(x = Attr46)) + labs(x= "(current assets - inventory) / short-term liabilities") +
  geom_density(fill = "orange")
```

### Point Estimate
```{r}
mean(posteriors$Attr46)
```

```{r}
median(posteriors$Attr46)
```

```{r}
map_estimate(posteriors$Attr46)
```

```{r}
ggplot(posteriors, aes(x = Attr46)) + labs(x= "book value of equity / total liabilities") + 
  geom_density(fill = "orange") +
  # The mean in blue
  geom_vline(xintercept=mean(posteriors$Attr46), color="blue", size=1) +
  # The median in red
  geom_vline(xintercept=median(posteriors$Attr46), color="red", size=1) +
  # The MAP in purple
  geom_vline(xintercept=map_estimate(posteriors$Attr46), color="purple", size=1)
```

### Uncertainty

```{r}
range(posteriors$Attr46)
```

```{r}
hdi(posteriors$Attr46, ci=0.89)
```
```{r}
rope(posteriors$Attr46, range = c(-20, 20), ci=0.89)
```


```{r}
training_data
```

## Stats Modelling

```{r}
library(ggplot2)
library(ggformula)
```

```{r}
gf_boxplot(class ~ Attr46, data=training_data)
```


```{r}
```












