---
title: "R Notebook"
output: html_notebook
---

```{r}
coreset_df <- read.csv('../data/coreset_train.csv')
coreset_df
```

```{r}
table(coreset_df$class)
```


```{r}
library(tidyverse)
library(caret)
library(GGally)
library(ggplot2)
library(corrplot)
library(bayesplot)
theme_set(bayesplot::theme_default(base_family = "sans"))
library(rstanarm)
options(mc.cores = parallel::detectCores())
library(loo)
library(projpred)
SEED=42
```


```{r}
t_prior <- student_t(df = 7, location = 0, scale = 2.5)
```

```{r}
post_full_coreset <- stan_glm(class ~ . , data = coreset_df,
                 family = binomial(link = "logit"), 
                 prior = t_prior, prior_intercept = t_prior,
                 cores=4, seed = 42)
```

```{r}
summary(post_full_coreset)
```

```{r}
prior_summary(post_full_coreset)
```


```{r}
pp_check(post_full_coreset, "dens_overlay")
```

```{r}
pp_check(post_full_coreset, "stat")
```

## Test now

```{r}
bankruptcy_test <- read_csv('../data/bankruptcy_test_am.csv')
bankruptcy_test <- select(bankruptcy_test, -X1)
bankruptcy_test
```
```{r}
table(bankruptcy_test$class)
```


```{r}
bankruptcy_test_x <- select(bankruptcy_test, -class)
dim(bankruptcy_test_x)
```


```{r}
test_pred <- posterior_predict(post_full_coreset, newdata = bankruptcy_test_x)
```

```{r}
dim(test_pred)
hist(test_pred)
```

```{r}
pred <- colMeans(test_pred)
pr <- as.integer(pred >= 0.5)
```

```{r}
table(pr)
```

```{r}
true_pr <- bankruptcy_test$class
table(true_pr)
```

```{r}
table(true_pr, pr)
```

```{r}
bayes_R2 <- function(fit) {
  mupred <- rstanarm::posterior_linpred(fit, transform = TRUE)
  var_mupred <- apply(mupred, 1, var)
  if (family(fit)$family == "binomial" && NCOL(y) == 1) {
      sigma2 <- apply(mupred*(1-mupred), 1, mean)
  } else {
      sigma2 <- as.matrix(fit, pars = c("sigma"))^2
  }
  var_mupred / (var_mupred + sigma2)
}
```


```{r}
y <- coreset_df$class
round(median(bayesR2<-bayes_R2(post_full_coreset)), 2)
```

```{r}
pxl<-xlim(0,1)
mcmc_hist(data.frame(bayesR2), binwidth=0.02) + pxl +
    scale_y_continuous(breaks=NULL) +
    xlab('Bayesian R2') +
    geom_vline(xintercept=median(bayesR2))
```


```{r}
library(MLmetrics)
```

```{r}
ConfusionMatrix(pr, true_pr)
```

```{r}
Precision(true_pr, pr)
```

```{r}
Recall(true_pr, pr)
```

## Plotting and analysing
```{r}
plot(post_full_coreset, "areas")
```

```{r}
coef(post_full_coreset)
```

```{r}
posterior_interval(post_full_coreset)
```

## Bayesian Variable Selection
```{r}
vs_coreset <- varsel(post_full_coreset, method='forward')
```

```{r}
vs_coreset$vind
```


## loo

```{r}
lpost1 <- readRDS("../model/post1.rds")
```

```{r}
loo(lpost1, post_full_coreset)
```
## Apply neural network to Coreset

### Pre-process - factor and scale data



```{r}
training_data <- read_csv('../data/coreset_train.csv')
head(training_data)
```
```{r}
test_data <- select(read_csv('../data/bankruptcy_test_am.csv'), -X1)
head(test_data)
```



```{r}
normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}
```


```{r}
training_data_pp <- as.data.frame(lapply(training_data, normalize))
test_data_pp <- as.data.frame(lapply(test_data, normalize))

```




## Neural Network Classifier
```{r}
library('neuralnet')
```



```{r}
nn <- neuralnet(class ~ ., data=training_data_pp, hidden=c(32,16,8,4), linear.output=FALSE, threshold=0.01)
plot(nn)
```


```{r}
nn.results <- compute(nn, test_data_pp)
results <- data.frame(actual = test_data_pp$class, prediction = nn.results$net.result)
results
```

```{r}
roundedresults<-sapply(results,round,digits=0)
roundedresultsdf=data.frame(roundedresults)
attach(roundedresultsdf)
table(actual,prediction)
```


```{r}
```


```{r}
```


```{r}
```

