---
title: "R Notebook"
output: html_notebook
---

```{r}
set.seed(42)
```


```{r}
library(dplyr)
```


```{r}
setwd("~/Projects/companies-bankruptcy-forecast/src")
```

# Read all the data
```{r}
bankruptcy_data <- read.csv('../data/bankruptcy_Train.csv')
head(bankruptcy_data)
```

```{r}
summary(bankruptcy_data)
```


# Pre-process : Scale the data

```{r}
na.omit(bankruptcy_data)
```


```{r}
# removing those observation rows with 0 in any of the variables
for (i in 1:64) {
      bankruptcy_data <- bankruptcy_data[which(bankruptcy_data[, i] != 0), ]
}
```

```{r}
dim(bankruptcy_data)
```


```{r}

# scale the covariates for easier comparison of coefficient posteriors

for (i in 1:64) {
      bankruptcy_data[i] <- scale(bankruptcy_data[i])
}

```


```{r}
dim(bankruptcy_data)
```

```{r}
bankruptcy_data
```


```{r}
str(bankruptcy_data)
```

## Make "class" to be factor type and create x and y variables

```{r}
bankruptcy_data$class <- factor(bankruptcy_data$class)
# preparing the inputs
x <- model.matrix(class ~ . - 1, data = bankruptcy_data)
y <- bankruptcy_data$class
```

```{r}
dim(bankruptcy_data)
head(bankruptcy_data)
```


# Take smaller dataset sample for development purpose

```{r}
bankruptcy_small <- bankruptcy_data %>% group_by(class) %>% sample_frac(.08)
str(bankruptcy_small)
```


```{r}
typeof(bankruptcy_data)
```



```{r}
table(bankruptcy_small$class)
```

```{r}
bankruptcy_train <- bankruptcy_small %>% group_by(class) %>% sample_frac(.70)
bankruptcy_train
```


```{r}
table(bankruptcy_train$class)
```



```{r}
bankruptcy_test <- anti_join(bankruptcy_small %>% group_by(class) %>% sample_frac(.90), bankruptcy_train)
bankruptcy_test
```

```{r}
table(bankruptcy_test$class)
```

# Get dimensions
```{r}

n=dim(bankruptcy_train)[1]
p=dim(bankruptcy_train)[2]
#str(bankruptcy_train)

```


```{r}
dim(bankruptcy_train)
```

```{r}
names(bankruptcy_train)
```


```{r}
typeof(bankruptcy_train)
```


# A Bayesian logistic regression model 



```{r}
library(tidyverse)
library(caret)
library(GGally)
library(ggplot2)
library(corrplot)
library(bayesplot)
theme_set(bayesplot::theme_default(base_family = "sans"))
library(rstanarm)
options(mc.cores = parallel::detectCores())
library(loo)
library(projpred)
SEED=42
```
```{r}
library(broom)
```


```{r}
t_prior <- student_t(df = 7, location = 0, scale = 2.5)
post1 <- stan_glm(class ~ . , data = bankruptcy_train,
                 family = binomial(link = "logit"), 
                 prior = t_prior, prior_intercept = t_prior,
                 seed = 42)
```

```{r}
summary(post1)
```


# PPC

```{r}
pp_check(post1, "dens_overlay")
```
```{r}
pp_check(post1, "stat")
```

