---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(caret)
library(GGally)
library(ggplot2)
library(corrplot)
library(bayesplot)
theme_set(bayesplot::theme_default(base_family = "sans"))
library(rstanarm)
options(mc.cores = parallel::detectCores())
library(loo)
library(projpred)

library(bayestestR)
SEED=42
set.seed(42)
```


```{r}
training_data <- select(read_csv('../data/bankruptcy_train_am.csv'), -X1)
test_data <- select(read_csv('../data/bankruptcy_test_am.csv'), -X1)
```

```{r}
head(training_data)
```
```{r}
head(test_data)
```


### Pre-process - factor  data

```{r}
training_data$class <- factor(training_data$class, levels = c(0,1))
test_data$class <- factor(test_data$class, levels = c(0,1))
```



## Build rstanarm model with selected variables RPART

```{r}
model_bayes_1 <- stan_glm(class ~ Attr24 + Attr25 + Attr26 + Attr21 + Attr34 + Attr5 + Attr46 , 
                          data = training_data, family = binomial(link = "logit"), 
                          cores=4, seed = 42)
```


```{r}
summary(model_bayes_1)
```


```{r}
prior_summary(model_bayes_1)
```

```{r}
describe_posterior(model_bayes_1)
```


In-sample
```{r}
model_bayes_1_output<-predict(model_bayes_1, data=training_data, type='response')
model_bayes_1_output <- as.integer(model_bayes_1_output >= 0.5)
cat("Confusion Matrix: ") 
table(training_data$class, model_bayes_1_output)

cat("\n Accuracy: ", mean(training_data$class == model_bayes_1_output))
```

Test
```{r}
model_bayes_1_output_test<-predict(model_bayes_1, data=test_data, type='response')
model_bayes_1_output_test <- as.integer(model_bayes_1_output_test >= 0.5)
cat("Confusion Matrix: ") 
table(test_data$class, model_bayes_1_output_test)

cat("\n Accuracy: ", mean(test_data$class == model_bayes_1_output_test))

```

```{r}
t1 <- posterior_predict(model_bayes_1, newdata = test_data[1, -65])
```

```{r}
summary(t1)
```


```{r}
res <- as.integer(t1 >= 0.5)
res
```

```{r}
table(t1)
```

```{r}
test_data[3, ]
```


```{r}
positives <- filter(test_data, class==1)
```

```{r}
positives[1,]
```

```{r}
p1 <- posterior_predict(model_bayes_1, newdata = positives[1, -65] )
```

```{r}
table(p1)
```

```{r}
median(p1)
```


```{r}
map_estimate(p1)
```


```{r}
pp_check(model_bayes_1, newdata=positives[1, -65])
```


```{r}
posterior_predict()
```

```{r}
simple <- lm (class ~ ., data=training_data)
```

```{r}
summary(simple)
```

```{r}

```

