---
title: "R Notebook"
output: html_notebook
---

```{r}
set.seed(42)
```


```{r}
library(dplyr)
```


```{r}
setwd("~/Projects/companies-bankruptcy-forecast/src")
```

# Read all the data
```{r}
bankruptcy_data <- read.csv('../data/bankruptcy_Train.csv')
head(bankruptcy_data)
```

```{r}
#summary(bankruptcy_data)
```


# Pre-process : Scale the data

```{r}
na.omit(bankruptcy_data)
```


```{r}
# removing those observation rows with 0 in any of the variables
for (i in 1:64) {
      bankruptcy_data <- bankruptcy_data[which(bankruptcy_data[, i] != 0), ]
}
```

```{r}
dim(bankruptcy_data)
```


```{r}

# scale the covariates for easier comparison of coefficient posteriors

for (i in 1:64) {
      bankruptcy_data[i] <- scale(bankruptcy_data[i])
}

```


```{r}
dim(bankruptcy_data)
```

## Make "class" to be factor type and create x and y variables

```{r}
bankruptcy_data$class <- factor(bankruptcy_data$class)
# preparing the inputs
x <- model.matrix(class ~ . - 1, data = bankruptcy_data)
y <- bankruptcy_data$class
```

```{r}
dim(bankruptcy_data)
head(bankruptcy_data)
```


# Take smaller dataset sample for development purpose

```{r}
bankruptcy_small <- bankruptcy_data %>% group_by(class) %>% sample_frac(.8)
```


```{r}
typeof(bankruptcy_data)
```



```{r}
table(bankruptcy_small$class)
```



```{r}
bankruptcy_train <- bankruptcy_small %>% group_by(class) %>% sample_frac(.70)
bankruptcy_train
```


```{r}
table(bankruptcy_train$class)
```



```{r}
bankruptcy_test <- anti_join(bankruptcy_small %>% group_by(class) %>% sample_frac(.90), bankruptcy_train)
bankruptcy_test
```

```{r}
table(bankruptcy_test$class)
```

# Get dimensions
```{r}

n=dim(bankruptcy_train)[1]
p=dim(bankruptcy_train)[2]
#str(bankruptcy_train)

# n=dim(bankruptcy_data)[1]
# p=dim(bankruptcy_data)[2]

```


```{r}
dim(bankruptcy_train)
```

```{r}
names(bankruptcy_train)
```


```{r}
typeof(bankruptcy_train)
```


# A Bayesian logistic regression model 



```{r}
library(tidyverse)
library(caret)
library(GGally)
library(ggplot2)
library(corrplot)
library(bayesplot)
theme_set(bayesplot::theme_default(base_family = "sans"))
library(rstanarm)
options(mc.cores = parallel::detectCores())
library(loo)
library(projpred)
SEED=42
```
```{r}
library(broom)
```


```{r}
dim(bankruptcy_train)
```


```{r}
t_prior <- student_t(df = 7, location = 0, scale = 2.5)

## Development
post1 <- stan_glm(class ~ . , data = bankruptcy_train,
                 family = binomial(link = "logit"), 
                 prior = t_prior, prior_intercept = t_prior,
                 cores=4, seed = 42)

## ALL DATA
# post1 <- stan_glm(class ~ . , data = bankruptcy_data,
#                  family = binomial(link = "logit"), 
#                  prior = t_prior, prior_intercept = t_prior,
#                  seed = 42, cores=4)

```

```{r}
summary(post1)
```
```{r}
prior_summary(post1)
```


## PPC

```{r}
pp_check(post1, "dens_overlay")
```
```{r}
pp_check(post1, "stat")
```

## Test!!!!


```{r}
### ALL TEST DATA
#bankruptcy_test <- read_csv('../data/bankruptcy_Test_X.csv')
```


```{r}
dim(bankruptcy_test)
```


```{r}
table(bankruptcy_test$class)
```

```{r}
# bankruptcy_test_x <- select(bankruptcy_test, -ID) # Remove ID Column
dim(bankruptcy_test_x)
```


```{r}
bankruptcy_test <- ungroup(bankruptcy_test)
dim(bankruptcy_test)
 
```
```{r}
bankruptcy_test_x <- select(bankruptcy_test, -class)
dim(bankruptcy_test_x)
```


```{r}
posterior <- posterior_predict(post1, newdata = bankruptcy_test_x)

```

```{r}
dim(posterior)
```

```{r}
hist(posterior)
```

```{r}
#bankruptcy_test$class
```


```{r}
pred <- colMeans(posterior)
pr <- as.integer(pred >= 0.5)
```

```{r}
table(pr)
```

```{r}
true_pr <- bankruptcy_test$class
table(true_pr)
```


```{r}
table(true_pr, pr)
```

```{r}
library(MLmetrics)
```

```{r}
ConfusionMatrix(pr, true_pr)
```

```{r}
Precision(true_pr, pr)
```

```{r}
Recall(true_pr, pr)
```

## Store Model, Train and Test Dataframes for future model comparison
```{r}
dim(bankruptcy_train)
```


```{r}
write.csv(bankruptcy_train, "../data/bankruptcy_train_am.csv")
```

```{r}
dim(bankruptcy_test)
```

```{r}
write.csv(bankruptcy_test, "../data/bankruptcy_test_am.csv")
```

```{r}
#post1@stanmodel@dso <- new("cxxdso") ## Didn't work
saveRDS(post1, file = "../model/post1.rds")
```

```{r}
lpost1 <- readRDS("../model/post1.rds")
```

```{r}
summary(lpost1)
```
```{r}
loo(lpost1)
```

```{r}
loo(post1)
```

## RSquared (https://avehtari.github.io/ROS-Examples/Rsquared/rsquared.html#Toy_logistic_regression_example,_n=20)

```{r}
bayes_R2 <- function(fit) {
  mupred <- rstanarm::posterior_linpred(fit, transform = TRUE)
  var_mupred <- apply(mupred, 1, var)
  if (family(fit)$family == "binomial" && NCOL(y) == 1) {
      sigma2 <- apply(mupred*(1-mupred), 1, mean)
  } else {
      sigma2 <- as.matrix(fit, pars = c("sigma"))^2
  }
  var_mupred / (var_mupred + sigma2)
}
```

```{r}
round(median(bayesR2<-bayes_R2(post1)), 2)
```

```{r}
pxl<-xlim(0,1)
mcmc_hist(data.frame(bayesR2), binwidth=0.02) + pxl +
    scale_y_continuous(breaks=NULL) +
    xlab('Bayesian R2') +
    geom_vline(xintercept=median(bayesR2))
```




## Variable Selection
```{r}
vs_post1$vind
```

```{r}
varsel_plot(vs_post1, stats=c('elpd', 'acc'), deltas=F)
```




