---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
```


```{r}
train_data <- read.csv('../data/coreset_train.csv')
head(train_data)
```


```{r}
train_class <- train_data[,65]
head(train_class)
```


```{r}
train_data <- train_data[,-65]
head(train_data)
```


```{r}
train_data <- scale(train_data)
colnames(train_data) <- NULL
train_data <- as.matrix(train_data)
head(train_data)
```



```{r}
library(BLNN)
```



```{r}
ClassNet<-BLNN_Build(ncov=64, nout=1, hlayer_size = 16,
                      actF = "tanh",
                      costF = "crossEntropy",
                      outF = "sigmoid",
                      hp.Err = 10, hp.W1 = .5, hp.W2 = .5,
                      hp.B1 = .5, hp.B2 = .5)
```


```{r}
n.par <- length(BLNN_GetWts(ClassNet))
chains <- 1
initials<- lapply(1:chains, function(i) rnorm(n.par))
```


```{r}
ClassHMC <- BLNN_Train(NET = ClassNet,
                          x = train_data,
                          y = train_class,
                          iter = 11,
                          init = initials,
                          chains = 1,
                          algorithm = "HMC",
                          display = 0,cores = 2,control = list(adapt_delta = 0.8,
                                                      Lambda = 0.005,
                                                      stepsize=5,
                                                      gamma=2)
                        )
```


```{r}
```


```{r}
```


```{r}
```

