---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
set.seed(42)
```


```{r}
training_data <- select(read_csv('../data/bankruptcy_train_am.csv'), -X1)
test_data <- select(read_csv('../data/bankruptcy_test_am.csv'), -X1)
```

```{r}
head(training_data)
```
```{r}
head(test_data)
```

```{r}
inner_join(training_data, test_data)
```

```{r}
logitMod <- glm(class ~ ., data=training_data, family=binomial(link="logit"))

```

```{r}
predicted <- predict(logitMod, test_data, type="response")
```

```{r}
length(predicted)
```

```{r}
predicted_scaled <- as.integer(predicted >= 0.5)
```

```{r}
table(predicted_scaled)
```

```{r}
true_pr <- test_data$class
table(true_pr, predicted_scaled)
```

## Stepwise variable selection

```{r}
library(MASS)
step.model <- logitMod %>% stepAIC(trace = FALSE)
coef(step.model)
```

```{r}
coef(step.model)
```


```{r}
predicted_step <- predict(step.model, test_data, type="response")
```

```{r}
predicted_step_scaled <- as.integer(predicted_step>= 0.5)
table(predicted_step_scaled)
```
```{r}
table(true_pr, predicted_step_scaled)
```

```{r}

```

