---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(tidyverse)
set.seed(42)
```


```{r}
training_data <- select(read_csv('../data/bankruptcy_train_am.csv'), -X1)
test_data <- select(read_csv('../data/bankruptcy_test_am.csv'), -X1)
```

```{r}
head(training_data)
```
```{r}
head(test_data)
```


### Pre-process - factor and scale data



```{r}
training_data$class <- factor(training_data$class, levels = c(0,1))
test_data$class <- factor(test_data$class, levels = c(0,1))
```


```{r}
head(training_data)
head(test_data)
```



## SVM Classify -
```{r}
library('e1071')
```


```{r}
svm_model <- svm(class ~ ., data=training_data, type = 'C-classification', kernel = "radial")

```


```{r}
predicted_train <- predict(svm_model, newdata=training_data[,-65])
```


```{r}
table(training_data$class, predicted_train)
MLmetrics::Accuracy(y_pred = predicted_train, y_true = training_data$class)
MLmetrics::Precision(training_data$class, predicted_train)
MLmetrics::Recall(training_data$class, predicted_train)
MLmetrics::F1_Score(training_data$class, predicted_train)
```


```{r}
predicted <- predict(svm_model, newdata=test_data[,-65])
```

```{r}
table(test_data$class, predicted)
MLmetrics::Accuracy(y_pred = predicted, y_true = test_data$class)
MLmetrics::Precision(test_data$class, predicted)
MLmetrics::Recall(test_data$class, predicted)
MLmetrics::F1_Score(test_data$class, predicted)
```


```{r}
table(predicted)
```

```{r}
true_pr <- test_data$class
table(true_pr, predicted)
```


```{r}

```

